session_name: thanhnguyen2187
windows:

- focus: 'true'
  layout: 3d02,174x45,0,0[174x34,0,0,0,174x10,0,35,3]
  options: {}
  panes:
  - nvim -S
  - null
  start_directory: /home/thanh/Projects/thanhnguyen2187
  window_name: writing

- layout: c242,174x45,0,0,5
  options: {}
  panes:
  - null
  start_directory: /home/thanh
  window_name: something
